### PR TITLE
Create state lenses (implicit/explicit)

### LINKED ISSUE #74: Feature reducer improvements / State lenses
Hello David. As I teased on twitter, we have been using a different kind of sub/feature reducer. I noticed that the sub reducers that are already in ReduxSimple really dispatch to the type of the property, which led to our homegrown reducer for "parts of the state", with a few differences.

1. You define the sub part by a slicer and a joiner function
2. The sub-reducer can be restricted to a base action, so that its properties can be used to direct to a dynamic part of the state
3. We're using the Builder pattern to avoid repeating the State type

We're using the name "LensedReducer" internally, but I'm pretty sure we're not using the concept of the functional lense correctly here.
Here's how you'd define such a thing:

```cs
        public static LensedReducer<State, StateElement, ElementBaseAction> BuildElementReducer()
        {
            return ReducerBuilder.ActionDependentLens<State, StateElement, ElementBaseAction>(
                (state, action) => state.Parts[action.Index],
                (state, newSilo, action) => state.With(new { Parts= state.Parts.SetItem(action.Index, newSilo) })
            );
        }
```

Adn we use that like this to generate a list of Ons:

```cs
            return BuildElementReducer()
                .On<ActionA>(SetAggregateSiloDenotation)
                .On<ActionB>(SetAggregateSiloCode)
                .ToList();
```

Here are the classes:

```cs
    public class LensedReducer<TState, TSlicedState, TBaseAction>
        where TState : class, new()
        where TBaseAction : class
    {
        private readonly Func<TState, TBaseAction, TSlicedState> slicer;
        private readonly Func<TState, TSlicedState, TBaseAction, TState> joiner;
        private readonly ImmutableList<On<TState>> reducers = ImmutableList<On<TState>>.Empty;

        public LensedReducer(Func<TState, TBaseAction, TSlicedState> slicer, Func<TState, TSlicedState, TBaseAction, TState> joiner)
            : this(slicer, joiner, ImmutableList<On<TState>>.Empty)
        {
        }

        private LensedReducer(Func<TState, TBaseAction, TSlicedState> slicer, Func<TState, TSlicedState, TBaseAction, TState> joiner, ImmutableList<On<TState>> previous)
        {
            this.slicer = slicer;
            this.joiner = joiner;
            this.reducers = previous;
        }

        public LensedReducer<TState, TSlicedState, TBaseAction> On<TAction>(Func<TSlicedState, TAction, TSlicedState> handler)
            where TAction : class, TBaseAction
        {
            TState Reduce(TState state, TAction action)
            {
                var oldSlicedState = slicer(state, action);
                var newSlicedState = handler(oldSlicedState, action);
                return joiner(state, newSlicedState, action);
            }

            var withNewReducer = reducers.Add(ReduxSimple.Reducers.On<TAction, TState>(Reduce));
            return new LensedReducer<TState, TSlicedState, TBaseAction>(slicer, joiner, withNewReducer);
        }

        public IReadOnlyList<On<TState>> ToList()
        {
            return reducers;
        }
    }

    static class ReducerBuilder
    {
        /// <summary>
        /// Create a lense that always focuses the same part of the state
        /// </summary>
        public static LensedReducer<TState, TSlicedState, object> StaticLens<TState, TSlicedState>(
            Func<TState, TSlicedState> slicer, Func<TState, TSlicedState, TState> joiner)
            where TState : class, new()
        {
            return new LensedReducer<TState, TSlicedState, object>(
                (state, _) => slicer(state),
                (state, sliced, _) => joiner(state, sliced));
        }

        /// <summary>
        /// Create a lense that can use the action to focus specific parts of the state
        /// </summary>
        public static LensedReducer<TState, TSlicedState, TBaseAction> ActionDependentLens<TState, TSlicedState, TBaseAction>(
            Func<TState, TBaseAction, TSlicedState> slicer,
            Func<TState, TSlicedState, TBaseAction, TState> joiner
            )
            where TState : class, new()
            where TBaseAction : class
        {
            return new LensedReducer<TState, TSlicedState, TBaseAction>(
                slicer, joiner);
        }
    }
```

What do you think?

### PR DESCRIPTION
**Pull request by Odonno**
Ey @ltjax

I started to create feature state lenses like we discussed. Here is what I am currently headed.

I still need to do some stuff before completing the PR:

* [x] implement API additions (lenses + pattern Builder) 
* [x] add XML doc on the API addition
* [x] update Sample app documentation
* [x] update readme documentation
* [x] update tests (current vs new ones for implicit/explicit lenses)

So, I managed to add two versions for implicit lense (pretty much like what we have now) and explicit lenses (both feature selector and state reducer). I also managed to include the pattern Builder so the code looks even simpler now. 

Tell me what you think!

Closes #74

### CODE REVIEW

**Comment by Odonno** [comment]
Seems good to me.

Also, this PR does not introduce breaking changes sinon the old `CreateSubReducers` function is marked as `[Obsolete]` at the moment.

**Comment by ltjax** [comment]
Hey there! Sorry it took me so long to get back to this. Been a busy week.
It looks like a nice improvement, but the thing that I'm sorely missing is the ability to specify a base action for the sub-reducer. This is critical for our application. It allows you to properly work with lists in your state without duplicating the dispatch to the correct index all the time.
I'm still not a big fan of the way you derive the write-back in the implicit lens, I think this: https://stackoverflow.com/questions/671968/retrieving-property-name-from-lambda-expression is a better solution. Either way, is there any reason why you did not implement the implicit lens based on the explicit one?

**Comment by Odonno** [comment]
Hum, I am sorry, I am having to see what you ask and what you expect.

On the most part, I think you suggest me to use `Expression`. I thought it was a custom class but it seems to be a part of the language. I will take a look at it to see what we can do with it.

For your last question, I did it tha tway because I have to reuse the `ISelector` and I didn't see how to do it differently. Again, I will look into it.

**Comment by ltjax** [comment]
No worries, I did not mean to discourage you. I'm perfectly fine with using our own implementation for now. The action thing is more important to me, the `Expression` thing is just a less hacky [Facade](https://en.wikipedia.org/wiki/Facade_pattern) really.
See the first code snippet in the [issue I posted](https://github.com/Odonno/ReduxSimple/issues/74) and how `action.Index` is used there for an example.

**Comment by Odonno** [comment]
Sorry. Been busy.

I looked at some examples of `Expression` and it seems interesting. But I don't see how to use it since I want a generic solution between the new `Func` way and most importantly the existing `ISelector` way.

On the other hand, I added new state lenses that use a `TAction` so you can apply a selector/reducer the same way you suggested in your issue. I slightly changed the order so here is how you can use it now:

```cs
public static IStateLens<State, StateElement> BuildElementReducer()
{
    return CreateSubReducers<State, ElementBaseAction, StateElement>(
        (state, action) => state.Parts[action.Index],
        (state, action, newSilo) => state.With(new { Parts = state.Parts.SetItem(action.Index, newSilo) })
    );
}
```

That will indeed create a state lens with a strict check on the type of the `Action`. I throw an `Exception` if the type does not match.

And then, you could use it like the any other state lens.

```cs
public static IEnumerable<On<State>> GetReducers()
{
    return BuildElementReducer()
        // As many Ons as you wish
        .ToList();
}
```

**Comment by ltjax** [comment]
Sorry for the delay.
That's a not bad start!
The main difference is that you only throw an exception when an action is dispatched, which is potentially a pretty late. My solution enforces this at compile time, which makes mismatches a little easier to spot. Does my solution have a drawback I'm not seeing?

I'll try to dig out a code sample for the Expressions..

**Comment by ltjax** [comment]
So I was thinking of using something like this:

```
public class ExpressionAccess<T>
{
    private static MemberExpression InitialMemberExpressionFor<X>(Expression<Func<T, X>> expression)
    {
        if (expression.Body is MemberExpression memberExpression)
            return memberExpression;

        if (expression.Body is UnaryExpression unaryExpression)
            return (MemberExpression)unaryExpression.Operand;

        throw new ArgumentException();
    }

    public static List<string> MemberListFor<X>(Expression<Func<T, X>> expression)
    {
        var parameter = expression.Parameters.Single();
        var memberExpression = InitialMemberExpressionFor(expression);

        var names = new List<string>();

        while (true)
        {
            names.Add(memberExpression.Member.Name);

            if (memberExpression.Expression == parameter)
                break;

            memberExpression = (MemberExpression)memberExpression.Expression;
        }

        // Turn outside-in to inside-out
        names.Reverse();
        return names;
    }

    public static dynamic ReadInnerValue(T container, List<string> memberList)
    {
        dynamic current = container;
        for (int i = 0; i < memberList.Count; ++i)
            current = current.GetType().GetProperty(memberList[i]).GetValue(current);
        return current;
    }

    public static void WriteInnerValue(T container, List<string> memberList, object value)
    {
        object current = container;

        // All but the last need to be read
        for (int i = 0; i < memberList.Count - 1; ++i)
            current = current.GetType().GetProperty(memberList[i]).GetValue(current);

        // The last one needs to be written
        current.GetType().GetProperty(memberList.Last()).SetValue(current, value);
    }
}
```

Of course, you'd need an immutable variant of `WriteInnerValue`. Let's call it `WithInnerValue`. You can then do something like:

```
public static IStateLens<TState, TStateElement> BuildReducerFrom<TState, TStateElement>(
  Expression<Func<TState,TStateElement>> expression)
{
    // Encode the expression as a string
    var path = ExpressionAccess<TState>.MemberListFor(expression);
    return CreateSubReducers<TState, object, TStateElement>(
        (state, _) => ExpressionAccess<TState>.ReadInnerValue(state, path), 
        (state, _, newValue) => ExpressionAccess<TState>.WithInnerValue(state, path, newValue)
    );
}
```

With that, you can do `BuildReducerFrom(state => state.Something.AnotherThing.EvenDeeper)`. Of course, it could be improved by also encoding other forms of "access", like supporting the index operator, but it's pretty powerful for a start.

**Comment by Odonno** [comment]
Since it is a while I updated this PR and the topic is quite complicated, I will merge this PR for now.

If you think there is a place for improvement @ltjax , we can continue this interesting debate on another issue or PR. :)

**Pull request merged**
